@if(!empty($responsiveCss))
<style>{{ $responsiveCss }}</style>
@endif
{{-- Dot grid: same hover effect as the CTA banner (resources/js/dot-grid.js, initialised on every .js-dot-grid), drawn in dark dots on the light background. --}}
{{-- Slider: resources/js/blocks/product-showcase-slider-section.js. The pagination dots are generated by slick, one per item. --}}
<section id="{{ $blockId }}"
  class="product-showcase-slider-section js-dot-grid product-showcase-slider-section--align-{{ $content_alignment }}"
  data-dot-style="varied"
  data-dot-color="dark"
  @if($section_style) style="{!! esc_attr($section_style) !!}" @endif>
  <canvas class="dot-grid-canvas" aria-hidden="true"></canvas>

  <div class="container">
    @if(count($items) > 0)
      <div class="product-showcase-slider-section__inner @if(count($items) > 1) has-slider @endif">
        <div class="product-showcase-slider-section__slider js-pss-slider" aria-label="{{ __('Product showcase', 'sage') }}">
          @foreach($items as $item)
            <div class="product-showcase-slider-section__slide">
              <div class="product-showcase-slider-section__item">
                @if($item['heading'])
                  <{{ $item['heading_level'] }} class="product-showcase-slider-section__heading">{!! nl2br(esc_html($item['heading'])) !!}</{{ $item['heading_level'] }}>
                @endif

                @if($item['image'])
                  <div class="product-showcase-slider-section__media">
                    <img src="{!! esc_url($item['image']['url']) !!}"
                      alt="{!! esc_attr($item['image']['alt']) !!}"
                      @if($item['image']['width']) width="{!! esc_attr($item['image']['width']) !!}" @endif
                      @if($item['image']['height']) height="{!! esc_attr($item['image']['height']) !!}" @endif
                      @if($loop->first) fetchpriority="high" @else loading="lazy" @endif
                      decoding="async"
                      class="product-showcase-slider-section__image">
                  </div>
                @endif
              </div>
            </div>
          @endforeach
        </div>

        {{-- Slick appends one dot per slide here (only when there is more than one item) --}}
        @if(count($items) > 1)
          <div class="product-showcase-slider-section__dots js-pss-dots"></div>
        @endif
      </div>
    @elseif($is_preview)
      <p class="product-showcase-slider-section__empty">{{ __('Product Showcase Slider: add a showcase item.', 'sage') }}</p>
    @endif
  </div>
</section>
